package fr.univ.fullswofng.controleur.order;

public enum OrderType {
    SHOW_MENU, SHOW_CONCENTRATION, SHOW_INITIAL_CONDITIONS, SHOW_MI_CONCENTRATION_COEFICIENT,
    SHOW_RELAXATION_PARAMETERS, SHOW_BALANCING_FUNCTION, SHOW_SPATIAL_INPUT_FOR_FLOW_CONCENTRATION,
    SHOW_RAINFALL_INPUT_FOR_FLOW_CONCENTRATION, SHOW_FLOW_INPUT_FOR_FLOW_CONCENTRATION, SHOW_CHEMICAL_INPUT_FOR_EXCHANGE_LAYER,
    SHOW_OUTPUT_FILE_NAME,
    DISABLE, ERREUR_NB_CLASSE, ERREUR_NB_INSTANT_SAUV, ERREUR_ORDRE_ESPACE, SHOW_CONCENTRATION_ENTRE,
    ERREUR_COEF_CIN, ERREUR_INSTANT_INITIALE, ERREUR_INSTANT_FINAL, DISABLE_COEFF_CIN,
    ERREUR_COEF_CONCENTRATION_MI,
    ERREUR_COEF_CI, ERREUR_COEF_MI,
    ERREUR_COEF_RPI, ERREUR_INTENSITE_PLUIE,
    ERREUR_INITIAL_APPORT_SPATIAL,ERREUR_FINAL_SPATIAL,ERREUR_COEF_CONSTANT_APPORT,
    ERREUR_DETACHABILITE,ERREUR_INSTANT_FINAL_APPORT_PLUIE,ERRUR_MASSE_SATURATION,ERREUR_SEUIL,ERREUR_COEF_PI,ERREUR_COEFF_B,
    ERREUR_SEUIL_DEBIT,ERREUR_COEF_FLUX,ERREUR_COEFF_PI,ERREUR_ENERGIE,ERREUR_INSTANT_FINALE,
    ERREUR_TAUX_DIFFUSION,ERREUR_PROFONDEUR,ERREUR_INSTANT_FINALE_APPORT,

}
